; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[env:main]
platform = espressif32
board = esp32dev
framework = arduino
build_src_filter = +<main.cpp>
monitor_speed = 115200

[env:led]
platform = espressif32
board = esp32dev
framework = arduino
build_src_filter = +<01_led/**>
monitor_speed = 115200

[env:rest]
platform = espressif32
board = esp32dev
framework = arduino
build_src_filter = +<02_rest/**>
build_flags = -Iinclude
monitor_speed = 115200
lib_deps =
	esp32async/AsyncTCP@^3.4.10
	esp32async/ESPAsyncWebServer@^3.11.2

[env:potentiometer]
platform = espressif32
board = esp32dev
framework = arduino
build_src_filter = +<03_potentiometer/**>
monitor_speed = 115200

[env:websocket]
platform = espressif32
board = esp32dev
framework = arduino
build_src_filter = +<04_websocket/**>
build_flags = -Iinclude
monitor_speed = 115200
lib_deps =
	esp32async/AsyncTCP@^3.4.10
	esp32async/ESPAsyncWebServer@^3.11.2

[env:mqtt]
platform = espressif32
board = esp32dev
framework = arduino
build_src_filter = +<05_mqtt/**>
build_flags = -Iinclude
monitor_speed = 115200
lib_deps =
	esp32async/AsyncTCP@^3.4.10
	esp32async/ESPAsyncWebServer@^3.11.2
	knolleary/PubSubClient@^2.8

[env:lora]
platform = espressif32
board = esp32dev
framework = arduino
build_src_filter = +<06_lora/**>
build_flags = -Iinclude
monitor_speed = 115200
lib_deps =
	sandeepmistry/LoRa@^0.8.0
