[env:led]
platform = espressif32
board = esp32dev
framework = arduino
serial_monitor_speed = 115200
build_src_dir = examples/01_led

[env:rest]
platform = espressif32
board = esp32dev
framework = arduino
serial_monitor_speed = 115200
build_src_dir = examples/03_rest

[env:potentiometer]
platform = espressif32
board = esp32dev
framework = arduino
serial_monitor_speed = 115200
build_src_dir = examples/02_potentiometer

[env:websocket]
platform = espressif32
board = esp32dev
framework = arduino
serial_monitor_speed = 115200
build_src_dir = examples/04_websocket

[env:mqtt]
platform = espressif32
board = esp32dev
framework = arduino
serial_monitor_speed = 115200
build_src_dir = examples/05_mqtt

[env:lora]
platform = espressif32
board = esp32dev
framework = arduino
serial_monitor_speed = 115200
build_src_dir = examples/06_lora
