#import "../../../common.typ": *

=== What is Mosquitto?

#block(
  radius: 6pt,
  inset: 5pt,
  stroke: 1pt,
)[Eclipse *Mosquitto* is a lightweight, open-source *MQTT broker*. It routes messages between publishers and subscribers using the *MQTT* pub/sub protocol _(the de-facto standard for IoT messaging)_.]

#v(0.3em)

- Written in C, very low footprint --- runs comfortably on a Raspberry Pi
- Supports MQTT v3.1/v3.1.1/v5, TLS, and WebSocket listeners
- Includes `mosquitto_pub` / `mosquitto_sub` CLI tools for quick testing
- Simple auth via password file, or plugin-based _(LDAP, JWT, etc.)_

#v(0.5em)
#line(length: 100%, stroke: 1pt + teal-color)
#v(0.5em)

#text(fill: teal-color, weight: "bold")[Alternatives]

- *EMQX* // clustering, dashboard, built-in rule engine, scales to millions of clients
- *HiveMQ* // enterprise-grade, strong monitoring/extension ecosystem
- *VerneMQ* // Erlang-based, clustering-focused, good HA support
- *NanoMQ* // ultra-lightweight, aimed at edge/embedded devices
- *AWS IoT Core / Azure IoT Hub* // managed cloud MQTT endpoints, no broker to maintain

#align(center)[#image("../../../assets/mqtt.png", width: 80%)]
#footer[Visual generated by AI.]

=== Installation

- Update package list and upgrade existing packages:
```bash
sudo apt update && sudo apt upgrade -y
```
- Install the broker (`mosquitto`) and CLI tools (`mosquitto_pub`, `mosquitto_sub`):
```bash
sudo apt install mosquitto mosquitto-clients -y
```
- Check the service status:
```bash
sudo systemctl status mosquitto
```
- You may need to enable and start the service manually:
```bash
sudo systemctl enable mosquitto
sudo systemctl start mosquitto
```

---

=== Configuration

- Main config file: `/etc/mosquitto/mosquitto.conf`
- Custom configs go in `/etc/mosquitto/conf.d/*.conf`
// - Minimal listener config placed in `/etc/mosquitto/conf.d/custom.conf`:
```config
listener 1883
allow_anonymous false
password_file /etc/mosquitto/passwd
```
- Restart after changes:
```
sudo systemctl restart mosquitto
```
- Check the broker status/logs:
```bash
sudo systemctl status mosquitto
sudo journalctl -u mosquitto -f
```

---

=== User Authentication

- Create the password file and first user:
```
sudo mosquitto_passwd -c /etc/mosquitto/passwd <username1>
```
- Add another user: _(no `-c`, or it overwrites the file)_
```
sudo mosquitto_passwd /etc/mosquitto/passwd <username2>
```
- Ensure `passwd` file has the proper owernship.
```bash
sudo chown mosquitto:mosquitto /etc/mosquitto/passwd
sudo chmod 600 /etc/mosquitto/passwd
```

---

=== Testing Pub/Sub

#info[It is recommended to install `tmux` for testing:
  ```bash
  sudo apt install tmux -y
  ```
]

- Subscribe _(terminal 1)_:
```
mosquitto_sub -h localhost -t test/topic -u <username> -P "<password>"
```
- Publish _(terminal 2)_:
```
mosquitto_pub -h localhost -t test/topic -m "hello" -u <username> -P "<password>"
```

=== MQTT Explorer

#text(fill: inkgray)[
  A free, cross-platform desktop client for *inspecting and debugging MQTT traffic* in real time — the visual counterpart to `mosquitto_pub` / `mosquitto_sub` on the command line.
]

#grid(
  columns: (1.05fr, 1fr),
  column-gutter: 1.4em,
  [
    #v(0.6em)
    #text(fill: teal, weight: "bold", size: 17pt)[Core features]
    #v(0.3em)

    - Live topic tree // _(topics render as an expandable hierarchy as messages arrive)_
    - Structured payload view // _(JSON payloads are pretty-printed and diffed on update)_
    - Publish / Subscribe pane // _(send test messages without touching a terminal)_
    - Wildcard subscriptions // _((`#`, `+`) to watch whole topic branches at once)_
    - Connection profiles // _(host, port, credentials, TLS, saved per broker)_
    - History graphing // _(for numeric topics over time)_

    #v(0.6em)
    #box(
      fill: light-red.lighten(88%),
      stroke: 1pt + light-red,
      radius: 6pt,
      inset: 10pt,
      width: 100%,
    )[
      #text(fill: light-red, weight: "bold", size: 15pt)[Why it matters here:]
      #v(0.2em)
      #text(size: 14pt)[
        It's our debugging lens for the ESP32 → Mosquitto → Node-RED chain — if a message doesn't show up in the tree, we know exactly where to look.
      ]
    ]
  ],
  [
    #align(center)[
      #box(
        stroke: 1pt + inkgray.lighten(60%),
        radius: 6pt,
        inset: 4pt,
      )[
        #image("../../../assets/mqtt-explorer.png", width: 100%)
      ]
      #v(0.3em)
      #text(size: 12pt, fill: inkgray.lighten(20%), style: "italic")[
        MQTT Explorer — topic tree and live payload view
      ]
      #v(0.1em)\
      #footer[#link("https://mqtt-explorer.com/")]
    ]
  ],
)
