#import "../../../common.typ": *

== IoT
#title-slide("Internet of Things", "Connecting the Physical World")

#topic[What is IoT?]

Network of physical devices — sensors, actuators, microcontrollers — that collect data and/or act on the physical world, connected to each other and/or the internet.

#note[#text(weight: "bold", fill: teal-color)[Core idea:] embed connectivity and processing into everyday objects, enabling remote monitoring, control, and automated decision-making.]
#example[smart thermostats, industrial sensors, wearables, connected cameras.]

---

#align(center)[#image("../../../assets/iot.png", width: 80%)]
#footer("Visual generated by AI")
---

#topic[IoT Architecture]

+ *Perception layer*: sensors, actuators, microcontrollers _(e.g. ESP32)_ — gathers raw data from the physical environment.
+ *Network layer*: transports data between devices, gateways, and the cloud _(WiFi, BLE, LoRa, cellular)_.
+ *Application layer*: processes, stores, and presents data — dashboards, alerts, automated actions.

---

#topic[IoT Communication Protocols]

- *HTTP/REST*: simple request/response, good for infrequent commands.
- *WebSocket*: persistent, full-duplex — used where low-latency bidirectional updates are needed _(e.g. live sensor dashboards)_.
- *MQTT*: lightweight publish/subscribe over TCP, designed for constrained devices and unreliable networks — the de-facto standard for IoT telemetry.
- *CoAP*: UDP-based, REST-like, built for very constrained devices.

---

#topic[Edge Computing in IoT]

- Processing data *on or near the device*, rather than sending everything to the cloud.
- #text(weight: "bold", fill: eg-green)[#checkmark Benefits:] lower latency, reduced bandwidth use, works with intermittent connectivity, improved privacy.
- Edge AI: running trained ML models directly on microcontrollers _(e.g. TinyML on ESP32)_ for local inference, no round trip to a server.

---

#topic[A Typical IoT Stack]

- *Device*: ESP32 _(or similar)_ reads sensors, runs local logic, optionally an on-device ML model.
- *Broker*: MQTT broker _(e.g. Mosquitto on a Raspberry Pi or cloud VM)_, routes messages between devices and applications.

#example[dashboard or service subscribing to topics, visualizing data, triggering alerts or actions.]

#title-slide(
  "From REST to WebSocket on ESP32",
  "A progressive web-server architecture: LED → Potentiometer",
)

=== REST and WS
#hl[Foundations: HTTP, REST, WebSocket]

#grid(
  columns: (1fr, 1fr, 1fr),
  gutter: 1.5em,
  [
    #text(weight: "bold", fill: accent)[HTTP] \
    - Request/response protocol;
    - Client asks, server answers, connection closes.
  ],
  [
    #text(weight: "bold", fill: accent)[RESTful] \
    An architectural style built on HTTP verbs (GET/POST) and stateless resources.
  ],
  [
    #text(weight: "bold", fill: accent)[WebSocket] \
    - A single persistent, full-duplex connection. \
    - Either side can push anytime.
  ],
)

---

#align(center)[#image("../../../assets/http.png", width: 80%)]
#footer[Visual generated by AI.]

---

#align(center)[#image("../../../assets/ws.png", width: 80%)]
#footer[Visual generated by AI.]

---

// #note("The three stages hereafter move from stateless HTTP calls toward a persistent, low-latency channel.")

==== LED Blink (RESTful over HTTP)
/ HTTP: handles this well: turning an LED on/off is an infrequent, stateless action — a plain request/response fits naturally.
/ RESTful: design: the LED is a *resource*.
- `GET /led/status` → read current state
- `POST /led` with `{"state": "on"}` → update state

#v(1em)
#align(center)[#text(fill: gray, size: 18pt)[One request → one response → done.]]

#important[WebSocket is unnecessary here: no continuous data, no need for the server to push updates unprompted.]

#url-block("codes/led-rest/")

---

#text(weight: "bold", fill: light-red)[Toolchain: PlatformIO]

#def[A cross-platform build system and library manager for embedded development. It replaces the Arduino IDE's manual library installs and board setup with a declarative `platformio.ini` file.
]
```bash
curl -fsSL https://raw.githubusercontent.com/platformio/platformio-core-installer/master/get-platformio.py -o get-platformio.py
python3 get-platformio.py
```
then add `~/.platformio/penv/bin` to `PATH`.

---

#info("One config file, reproducible builds — no more manual Library Manager clicks.")

- #text(weight: "bold", fill: light-red)[Project layout:] `platformio.ini` at the root, source in `src/main.cpp`, \
dependencies declared under `lib_deps`.
- #text(weight: "bold", fill: light-red)[Core commands:]
/ Build: `pio run`
/ Flash: `pio run --target upload`
/ Serial output: `pio device monitor`


#slide[
  ==== Potentiometer (WebSocket)

  / HTTP: becomes inefficient: polling repeatedly for a value that changes continuously wastes bandwidth and adds latency.
  / RESTful: polling would work but doesn't scale to real-time data.
  / WebSocket: solves it: one persistent connection, the ESP32 *pushes* new readings as they change — no repeated handshakes.
  #v(1em)
  #align(center)[#text(fill: gray, size: 18pt)[Same server, one new `/ws` endpoint added.]]
  #url-block("codes/pot-ws/")
]


#slide[
  === MQTT
  // #titlebar[MQTT: A Protocol Built for IoT]

  #text(fill: inkgray)[
    *MQTT* (Message Queuing Telemetry Transport) is a lightweight
    *publish/subscribe* messaging protocol, originally designed for
    constrained devices on unreliable networks.
  ]

  #v(0.6em)
  #grid(
    columns: (1fr, 1fr),
    column-gutter: 1.2em,
    box(
      fill: eg-green.lighten(88%),
      stroke: 1pt + eg-green,
      radius: 6pt,
      inset: 12pt,
      width: 100%,
    )[
      #text(fill: eg-green, weight: "bold")[Why it fits IoT]
      #v(0.3em)
      - Tiny header, minimal overhead per message
      - Devices don't need to know about each other
      - Handles flaky, low-bandwidth connections gracefully
      - One device can reach many listeners at once
    ],
    box(
      fill: maroon.lighten(90%),
      stroke: 1pt + maroon,
      radius: 6pt,
      inset: 12pt,
      width: 100%,
    )[
      #text(fill: maroon, weight: "bold")[MQTT vs. HTTP]
      #v(0.3em)
      - HTTP: pull-based, request → response
      - MQTT: push-based, event-driven
      - No polling — devices publish only when there's
      something to say
    ],
  )

  #notebox[][
    MQTT decouples *who sends* from *who receives* — a device
    publishes without knowing or caring who (if anyone) is
    listening.
  ]
]

#slide[
  #titlebar[Publish / Subscribe & Topics]

  #align(center)[
    #grid(
      columns: (1fr, auto, 1fr, auto, 1fr),
      align: horizon,
      column-gutter: 0.6em,
      box(
        fill: teal.lighten(85%),
        stroke: 1pt + teal,
        radius: 6pt,
        inset: 8pt,
      )[
        #text(fill: teal, weight: "bold", size: 14pt)[Publisher\ (e.g. ESP32)]
      ],
      text(fill: inkgray, size: 20pt)[→],
      box(
        fill: maroon.lighten(88%),
        stroke: 1pt + maroon,
        radius: 6pt,
        inset: 8pt,
      )[
        #text(fill: maroon, weight: "bold", size: 14pt)[Topic\ `sensors/temp`]
      ],
      text(fill: inkgray, size: 20pt)[→],
      box(
        fill: teal.lighten(85%),
        stroke: 1pt + teal,
        radius: 6pt,
        inset: 8pt,
      )[
        #text(fill: teal, weight: "bold", size: 14pt)[Subscriber(s)\ (e.g. Node-RED)]
      ],
    )
  ]
  #v(0.3em)
  #align(center)[
    #text(size: 12pt, fill: inkgray.lighten(20%), style: "italic")[
      a broker relays each message
    ]
  ]

  #v(0.3em)
  #text(fill: teal, weight: "bold", size: 17pt)[Topics are hierarchical]
  #v(0.3em)
  - Slash-separated, like a path: `home/livingroom/temperature`
  - Publishers and subscribers only need to agree on topic names, not on each other's existence

  #text(fill: teal, weight: "bold", size: 17pt)[Wildcards for subscribing]
  #v(0.3em)
  - `+` — matches exactly one level: `home/+/temperature`
  - `#` — matches everything below: `home/#`
  #notebox[][
    One subscriber can listen to an entire branch of devices (`home/#`) without knowing in advance how many there are.
  ]
]

#slide[
  #titlebar[Delivery Guarantees & Extra Features]

  #table(
    columns: (0.6fr, 1.4fr, 1.2fr),
    stroke: 0.5pt + gray,
    inset: 8pt,
    text(weight: "bold")[Level], text(weight: "bold")[Guarantee], text(weight: "bold")[Trade-off],
    [QoS 0], [At most once — fire and forget], [Lowest overhead, may drop],
    [QoS 1], [At least once — may duplicate], [Guaranteed, some overhead],
    [QoS 2], [Exactly once], [Highest overhead, no duplicates],
  )

  #v(0.7em)
  #grid(
    columns: (1fr, 1fr),
    column-gutter: 1.2em,
    box(
      fill: eg-green.lighten(88%),
      stroke: 1pt + eg-green,
      radius: 6pt,
      inset: 12pt,
      width: 100%,
    )[
      #text(fill: eg-green, weight: "bold")[Retained messages]
      #v(0.3em)
      #text(size: 14pt)[
        The broker keeps the last message on a topic, so a new subscriber gets the current state immediately — no need to wait for the next publish.
      ]
    ],
    box(
      fill: maroon.lighten(90%),
      stroke: 1pt + maroon,
      radius: 6pt,
      inset: 12pt,
      width: 100%,
    )[
      #text(fill: maroon, weight: "bold")[Last Will and Testament (LWT)]
      #v(0.3em)
      #text(size: 14pt)[
        A message the client pre-registers to be sent automatically if it disconnects unexpectedly — the standard way to detect a device going offline.
      ]
    ],
  )

  /*
  #notebox[][
  Retained messages give instant state on reconnect; LWT gives "device is offline" detection for free — both solve real problems specific to flaky, battery-powered, always-on-ish devices.
  ]
  */

  #url-block("codes/mqtt/")
]

---

#title-slide[LoRa & LoRaWAN][Long-Range, Low-Power Wireless for IoT]

#titlebar[What is LoRa?]

- *LoRa* (Long Range) — a proprietary spread-spectrum radio modulation, Chirp Spread Spectrum (CSS), developed by Semtech.
- Runs in unlicensed sub-GHz ISM bands: *868 MHz* (Europe, Africa, Middle East — ITU Region 1), *915 MHz* (US/Canada), 433/470 MHz regionally.
- Trades throughput for range and power: kilometers of reach at a few hundred bps to ~50 kbps.
- LoRa is the *physical layer only* — modulation and radio, nothing else.

#important[
  LoRa ≠ LoRaWAN. LoRa is the radio modulation (PHY). *LoRaWAN* is the open MAC/network protocol built on top of it, standardized by the LoRa Alliance. You can use raw LoRa point-to-point without ever touching LoRaWAN — that's exactly what the demo later in this section does.
]

#slide[
  #titlebar[Where It Fits]
  #align(center)[
    #table(
      columns: (auto, auto, auto, auto, auto),
      stroke: 0.5pt + gray,
      inset: 6pt,
      text(weight: "bold")[Technology],
      text(weight: "bold")[Range],
      text(weight: "bold")[Power],
      text(weight: "bold")[Data Rate],
      text(weight: "bold")[Topology],

      [Wi-Fi], [~50 m], [High], [High (Mbps)], [Star (AP)],
      [BLE], [~10-30 m], [Low], [Medium], [P2P / mesh],
      [LoRa / LoRaWAN], [2-15+ km], [Very low], [Very low (bps-kbps)], [Star-of-stars],
      [NB-IoT / LTE-M], [Cellular coverage], [Low-medium], [Low-medium], [Cellular],
      [Zigbee], [~10-100 m], [Low], [Medium], [Mesh],
    )
  ]
  #note[
    LoRa doesn't replace MQTT or WebSocket from earlier in this section — it replaces Wi-Fi/Ethernet as *how a device reaches the network in the first place*. MQTT still runs on top, just past the gateway.
  ]
]

#align(center)[#image("../../../assets/bandwidth-power-range.webp", width: 70%)]
#footer[Source: #link("mokolora.com/lora-and-wireless-technologies/")]

#slide[
  #titlebar[Why It Fits IoT]
  - *Long range* — several km in urban areas, 15+ km rural / line-of-sight.
  - *Low power* — years of battery life on a coin cell; suits battery- or energy-harvested sensors.
  - *Penetration* — sub-GHz propagates through walls and foliage better than 2.4 GHz Wi-Fi/BLE.
  - *Low data rate by design* — built for a sensor reading every few minutes, not a video stream. Trade-off, not a flaw.
  - *Star-of-stars topology* — many end devices → a handful of gateways → one network server (unlike Wi-Fi's single-hop AP model).

  #note[
    Same spirit as MQTT: devices don't need to know who's listening. Here the *gateway* does the decoupling, over the air, instead of a broker doing it over TCP.
  ]
]

#slide[
  #titlebar[Network Architecture]
  #align(center)[
    #block(
      fill: rgb("#eafaf1"),
      stroke: rgb("#1f9d55"),
      inset: 8pt,
      radius: 3pt,
    )[*End Devices* — sensors, ESP32 + LoRa radio]
    #v(0.25em) #text(size: 16pt)[↓ LoRa radio, unlicensed ISM band] #v(0.25em)
    #block(
      fill: rgb("#eafaf1"),
      stroke: rgb("#1f9d55"),
      inset: 8pt,
      radius: 3pt,
    )[*Gateway(s)* — concentrator, e.g. a Pi + RAK2287 HAT]
    #v(0.25em) #text(size: 16pt)[↓ IP backhaul — Ethernet / Wi-Fi / cellular] #v(0.25em)
    #block(
      fill: rgb("#eafaf1"),
      stroke: rgb("#1f9d55"),
      inset: 8pt,
      radius: 3pt,
    )[*Network Server* — ChirpStack / The Things Network]
    #v(0.25em) #text(size: 16pt)[↓ MQTT / HTTP webhook] #v(0.25em)
    #block(
      fill: rgb("#eafaf1"),
      stroke: rgb("#1f9d55"),
      inset: 8pt,
      radius: 3pt,
    )[*Application Server* — Mosquitto, Node-RED, Grafana]
  ]

  /*
  - One gateway commonly hears *thousands* of end devices — a very different scaling model from Wi-Fi access points.
  - The network server de-duplicates messages heard by multiple gateways and owns security/session state.
  */
]

#slide[
  #titlebar[Alternatives]
  *Other LPWAN radios*
  - Sigfox — proprietary, ultra-narrowband
  - NB-IoT / LTE-M — cellular, licensed spectrum, carrier-billed
  - Zigbee / Z-Wave — mesh, short range
  - Wi-SUN

  *LoRaWAN network servers*
  - The Things Network (TTN) — free community network, easiest workshop starting point
  - ChirpStack — open-source, self-hosted, pairs naturally with the Pi already running Mosquitto/Node-RED
  - Commercial: AWS IoT Core for LoRaWAN, Helium
]

#slide[
  #titlebar[Key Radio Parameters]
  - *Spreading Factor* (SF7–SF12) — higher SF means longer range and better sensitivity, but lower data rate and longer airtime. The main trade-off dial.
  - *Bandwidth* — 125 / 250 / 500 kHz; wider means faster but shorter range.
  - *Coding Rate* — forward error correction overhead (4/5 to 4/8).
  - Airtime roughly doubles with every step up in Spreading Factor — why an SF12 message sits on air dramatically longer than an SF7 one.
  - *ADR* (Adaptive Data Rate) — the network server tunes SF/power automatically for static, well-connected devices to save airtime and battery.

]

#slide(title: [MWE])[

  #note[
    Raw point-to-point LoRa — two radios talking directly, no gateway, no network server yet.
  ]

  #url-block("codes/lora/")

  #warning[
    Both radios must agree on frequency, spreading factor, bandwidth, and sync word — or they simply won't hear each other, with no error on either side.
  ]
]
